[write]
  concurrency = 10
  batch_size = 5000
  batch_interval = "0s"
  database = "stress"
  precision = "n"
  address = "localhost:8086"
  reset_database = true
  # doesnt do anything
  starting_point = "6m" # how far back in time to go

[[series]]
  point_count = 10 # number of points that will be written for each of the series
  measurement = "cpu"
  series_count = 100000

  tag_count = 20 # doesnt do anything yet

  [[series.tag]]
    key = "host"
    value = "idk"

  [[series.tag]]
    key = "location"
    value = "lame"

  [[series.field]]
    key = "value"
    type = "float64"

  [[series.field]]
    key = "percent"
    type = "int"

  [[series.field]]
    key = "idk"
    type = "bool"

  [[series.field]]
    key = "default"

[[series]]
  point_count = 10 # number of points that will be written for each of the series
  measurement = "mem"
  series_count = 100000

  [[series.tag]]
    key = "host"
    value = "idk"

  [[series.tag]]
    key = "location"
    value = "lame"

  [[series.field]]
    key = "value"
    type = "float64"

  [[series.field]]
    key = "loc"
    type = "float64"

  [[series.field]]
    key = "sunny"
    type = "bool"

  [[series.field]]
    key = "idk"
    type = "int"

# Currently not functional
[[query]]
  concurrency = 10
  measurement = "cpu"
  tag_key = "host"
  time_frame = "5m" # defaults to 0 which will query over all time
  statement = "SELECT count(value) FROM #{measurement} WHERE #{tag_key}=#{tag_value}" # needs work

[[query]]
  concurrency = 1
  statement = "SELECT count(value) FROM cpu" # needs work

